### PR TITLE
Add decimal.js as a note for JavaScript

### PR DESCRIPTION
**Pull request by bpierre**
Following https://github.com/erikwiffin/0.30000000000000004/issues/9#issuecomment-298282462

### CODE REVIEW

**Comment by erikwiffin** [comment]
Thanks!

**Comment by bpierre** [comment]
@erikwiffin You closed without merging, not sure if it’s a mistake?

**Comment by erikwiffin** [comment]
Definitely a mistake. Sorry about that.

**Comment by bpierre** [comment]
No worries! 👍

**Pull request merged**
