### PR TITLE
Add Elixir

### PR DESCRIPTION
**Pull request by OCannings**

### CODE REVIEW

**Comment by erikwiffin** [comment]
Someone else got to Elixir first. Sorry.

**Comment by OCannings** [comment]
Mine was first, this is an outrage! :P

**Comment by littleowllabs** [comment]
Someone else got to Elixir "second".

**Comment by erikwiffin** [comment]
Ah, sorry, github lists pull requests from most to least recent. I'll have to start merging from the bottom up now. :)

**Pull request closed without merging**
