### PR TITLE
Common Lisp isn't actually immune to this.

### PR DESCRIPTION
**Pull request by vendethiel**

### CODE REVIEW

**Comment by erikwiffin** [comment]
Mea culpa. I've been a bad project maintainer. When my site was posted to reddit and hacker news, I received a flood of enthusiastic pull requests for a bunch of new languages, corrections, and explanations. I got overwhelmed, and have not done a good job of handling those PRs.

To hopefully keep this from happening again, I've rewritten the site in jekyll so that future PRs should be less likely to merge conflict, and easier to manage.

I did my best to incorporate feedback from any open PRs, but I may have missed yours. If I did, or if your language has changed since you sent me this, feel free to send me a new request, and I'll do my best to be more responsive this time.

Thank you for your understanding.

**Comment by vendethiel** [comment]
I'll try to submit a new PR

**Comment by wobh** [comment]
Hi. I reviewed the Common Lisp standard documentation on floats, and although I don't see anywhere the standard mandates the accuracy of floating point arithmetic, I also can't reproduce the issue with `(- 1.2 0.1)` in any recent version of SBCL, CCL, Clisp, ECL, or ABCL for the Mac. There are, of course, other platforms and implementations, but if `(+ 0.1 0.2)` is accurately computed in them, I think `(- 1.2 0.1)` should be as well, or reported as a bug.

**Comment by vendethiel** [comment]
It's `(- 1.2 1.0)`. Note how it is `1.0` not `0.1`

**Comment by vendethiel** [comment]
I can reproduce this with SBCL and CLisp.

**Comment by wobh** [comment]
Doh! Thank you. I reproduced it in the other implementations as well!

**Pull request closed without merging**
