### PR TITLE
Added result for R

### PR DESCRIPTION
**Pull request by stefanedwards**

### CODE REVIEW

**Comment by stefanedwards** [comment]
Sorry, you are absolutely right. Here's an update. Have I done it correctly?

**Comment by erikwiffin** [comment]
Looks like you've got a merge conflict too. If you fix that, I can get this up on the site.

**Comment by stefanedwards** [comment]
I can't see any merge conflicts, so I am not sure what you want me to do.

**Comment by erikwiffin** [comment]
I can't merge it using the UI.

image

**Comment by stefanedwards** [comment]
Done?

**Pull request merged**
